In [3]:
import numpy as np
from rnncomp.dataman import *

fi = np.load("datasets/dataset_flatcls_0.5_2_3_0.npz")
desc = fi["class_desc"].item()
nengo_dat, nengo_cor = make_run_args_nengo(fi)
print(nengo_dat)
print(nengo_dat.shape)

[[[ 0.    0.    0.   ..., -1.   -1.   -1.  ]
  [ 0.    0.    0.   ..., -1.   -1.   -1.  ]]

 [[ 0.    0.    0.   ...,  1.    1.    1.  ]
  [ 0.    0.    0.   ...,  1.    1.    1.  ]]

 [[ 0.    0.    0.   ...,  0.25  0.25  0.25]
  [ 0.    0.    0.   ...,  0.25  0.25  0.25]]]
(3, 2, 510)


Desired output format: `[time_steps, 1, dimensions]`

In [6]:
dim_last = nengo_dat.reshape((3, 510, 2))
print(dim_last[0, :, :])

[[ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 ..., 
 [-1. -1.]
 [-1. -1.]
 [-1. -1.]]


In [12]:
comb = dim_last.reshape((3*510, 1, 2))
print("Chunk A")
print(comb[:510, 0, :])
print("Chunk B")
print(comb[510:2*510, 0, :])
print("Chunk C")
print(comb[2*510:3*510, 0, :])

Chunk A
[[ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 ..., 
 [-1. -1.]
 [-1. -1.]
 [-1. -1.]]
Chunk B
[[ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 ..., 
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]]
Chunk C
[[ 0.    0.  ]
 [ 0.    0.  ]
 [ 0.    0.  ]
 ..., 
 [ 0.25  0.25]
 [ 0.25  0.25]
 [ 0.25  0.25]]


In [33]:
t_steps = 10
n_classes = 3
sig_num = 1
pause_size = 5

In [16]:
print(nengo_cor)
print(nengo_cor[0])
print(nengo_cor.shape)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
[ 1.  0.  0.]
(3, 3)


In [27]:

re_cor = np.repeat(nengo_cor, t_steps, axis=0).reshape((-1, 1, 3))
print(re_cor[:3])
print(re_cor.shape)

[[[ 1.  0.  0.]]

 [[ 1.  0.  0.]]

 [[ 1.  0.  0.]]]
(60, 1, 3)


In [26]:
re_cor[1]

array([ 1.,  0.,  0.])

In [61]:
zer = np.zeros((n_classes*sig_num, n_classes, pause_size))
re_zer = np.repeat(nengo_cor, t_steps, axis=1).reshape((n_classes*sig_num, n_classes, t_steps))
cor = np.concatenate((zer, re_zer), axis=2)
print(cor)
print(cor.shape)

[[[ 0.  0.  0.  0.  0.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
  [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]

 [[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
  [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]

 [[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]]]
(3, 3, 15)


In [62]:
print(cor[0])

[[ 0.  0.  0.  0.  0.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]


In [63]:
t_last = cor.reshape((3, 1, -1))
print(t_last.shape)
print(t_last[:, 0, :10])

(3, 1, 45)
[[ 0.  0.  0.  0.  0.  1.  1.  1.  1.  1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]


In [64]:
t_first = d_last.T
print(t_first.shape)
print(t_first[:10, 0, 0])

(45, 1, 3)
[ 0.  0.  0.  0.  0.  1.  1.  1.  1.  1.]
